# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_project_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
