# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0005_auto_20181012_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tech_used',
            new_name='technologies_used',
        ),
    ]
