# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_auto_20181012_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
