# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0009_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo',
            new_name='recorded_demo',
        ),
    ]
